jobs:
  - name: test-script
    type: runSh
    steps:
     - TASK:
        - script: sleep 2m
  - name: do_token_test
    type: runSh
    steps:
    - IN: do_token
    - TASK:
      - script: printenv
      
  - name: simple-runsh-U1404
    type: runSh
    steps:
      - TASK:
        - script: sleep 2m
