jobs:
  - name: test-script
    type: runSh
    steps:
     - TASK:
         name: check_container
         runtime:
           container: true
           options:
             imageName: drydock/u16
             imageTag: v5.10.4
             pull: false
         script: ls
  - name: do_token_test
    type: runSh
    steps:
    - IN: do_token
    - TASK:
      - script: printenv
      
  - name: simple-runsh-U1404
    type: runSh
    steps:
      - TASK:
        - script: sleep 2m
