jobs:
  - name: test-script
    type: runSh
    steps:
     - TASK:
        - script: export x=1
    on_success:
        - script: sl
        - script: ls
  - name: do_token_test
    type: runSh
    steps:
    - IN: docker-cli-config
    - TASK:
      - script: printenv
