jobs:
  - name: test-script
    type: runSh
    steps:
     - TASK:
        - script: sleep 2
  - name: do_token_test
    type: runSh
    steps:
    - IN: do_token
    - TASK:
      - script: printenv
